# Generated by Django 2.0.7 on 2019-04-10 20:26

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP地址')),
                ('user_agent', models.TextField(default='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36', max_length=128, verbose_name='设备信息')),
                ('add', models.DateTimeField(auto_now_add=True, verbose_name='点击时间')),
            ],
            options={
                'verbose_name': '广告点击统计',
                'verbose_name_plural': '广告点击统计',
                'db_table': 'adclick',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_name', models.CharField(max_length=20, verbose_name='广告名')),
                ('image', models.ImageField(blank=True, upload_to='ad/', verbose_name='图片')),
                ('link', models.URLField(verbose_name='广告链接')),
                ('adtype', models.PositiveSmallIntegerField(blank=True, choices=[(0, '右侧方形广告'), (1, '左侧长条广告')], null=True, verbose_name='广告类型')),
                ('remark', models.TextField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('add', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('mod', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('end', models.DateTimeField(null=True, verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
                'db_table': 'advertisement',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.random, max_length=12, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='1~32个字', max_length=32, verbose_name='标题')),
                ('cover', models.ImageField(blank=True, upload_to='blog/cover/', verbose_name='封面')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容')),
                ('source', models.URLField(blank=True, help_text='如果转载, 则提供原文链接', null=True, verbose_name='原文链接')),
                ('is_fine', models.BooleanField(default=False, verbose_name='站长推荐')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('read', models.PositiveIntegerField(default=0, verbose_name='阅读数')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('add', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('mod', models.DateTimeField(auto_now=True, verbose_name='最后修改')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(help_text='1~12个字', max_length=12, verbose_name='类别')),
                ('add', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('mod', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP地址')),
                ('user_agent', models.CharField(default='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36', max_length=128, verbose_name='设备信息')),
                ('add', models.DateTimeField(auto_now_add=True, verbose_name='点击时间')),
            ],
            options={
                'verbose_name': '友链点击统计',
                'verbose_name_plural': '友链点击统计',
                'db_table': 'click',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=12, null=True, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, max_length=300, verbose_name='评论内容')),
                ('reply', DjangoUeditor.models.UEditorField(blank=True, max_length=300, verbose_name='作者回复')),
                ('add', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('rep', models.DateTimeField(blank=True, default=None, null=True, verbose_name='回复时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否可用')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coms', to='db.Blog', verbose_name='所属博客')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Expand',
            fields=[
                ('key', models.CharField(help_text='1~16字符', max_length=16, primary_key=True, serialize=False, verbose_name='键')),
                ('value', models.CharField(help_text='1~32字符', max_length=32, verbose_name='值')),
                ('remark', models.TextField(max_length=100, null=True, verbose_name='备注')),
                ('mod', models.DateTimeField(auto_now=True, verbose_name='上次变更')),
            ],
            options={
                'verbose_name': '拓展数据',
                'verbose_name_plural': '拓展数据',
                'db_table': 'expand',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('link', models.URLField(max_length=64, primary_key=True, serialize=False, verbose_name='链接')),
                ('link_name', models.CharField(max_length=32, verbose_name='链接名称')),
                ('cat', models.PositiveSmallIntegerField(choices=[(0, '公益链接'), (1, '个人主页'), (2, '商业广告')], default=0, verbose_name='链接类型')),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('add', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('mod', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
                'db_table': 'link',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=12, null=True, verbose_name='昵称')),
                ('email', models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, max_length=300, verbose_name='内容')),
                ('reply', DjangoUeditor.models.UEditorField(blank=True, max_length=300, null=True, verbose_name='站长回复')),
                ('add', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('rep', models.DateTimeField(blank=True, default=None, null=True, verbose_name='回复时间')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否可见')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='1~20个字', max_length=20, verbose_name='标题')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, verbose_name='详情')),
                ('add', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('mod', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可见')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='1~12个字', max_length=12, unique=True, verbose_name='标签')),
                ('add', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('mod', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('email', models.EmailField(help_text='最多32字符', max_length=32, primary_key=True, serialize=False, verbose_name='邮箱')),
                ('nickname', models.CharField(help_text='1~12个字', max_length=12, unique=True, verbose_name='昵称')),
                ('header', models.ImageField(blank=True, null=True, upload_to='header/', verbose_name='头像')),
                ('pwd', models.CharField(blank=True, max_length=20, null=True, verbose_name='密码')),
                ('desc', models.TextField(blank=True, help_text='200字描述一下自己', max_length=200, null=True, verbose_name='简介')),
                ('is_author', models.BooleanField(default=True, verbose_name='是否作者')),
                ('alipay', models.ImageField(blank=True, null=True, upload_to='dsm/alipay/', verbose_name='支付宝打赏码')),
                ('wechat', models.ImageField(blank=True, null=True, upload_to='dsm/wechat/', verbose_name='微信打赏码')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否可用')),
                ('mod', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('add', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '访客',
                'verbose_name_plural': '访客',
                'db_table': 'visitor',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Visitor', verbose_name='访客'),
        ),
        migrations.AddField(
            model_name='comment',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Visitor', verbose_name='评论者'),
        ),
        migrations.AddField(
            model_name='click',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Link', verbose_name='链接'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Visitor', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='blog',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cblogs', to='db.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tblogs', to='db.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='adclick',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Advertisement', verbose_name='广告'),
        ),
        migrations.CreateModel(
            name='TipAd',
            fields=[
            ],
            options={
                'verbose_name': '长条广告',
                'verbose_name_plural': '长条广告',
                'proxy': True,
                'indexes': [],
            },
            bases=('db.advertisement',),
        ),
        migrations.CreateModel(
            name='TopBlog',
            fields=[
            ],
            options={
                'verbose_name': '置顶博客',
                'verbose_name_plural': '置顶博客',
                'proxy': True,
                'indexes': [],
            },
            bases=('db.blog',),
        ),
    ]
