# Generated by Django 2.0.7 on 2019-04-02 21:36

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20190402_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Visitor', verbose_name='评论者'),
        ),
    ]
