# Generated by Django 2.0.7 on 2019-05-09 15:25

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20190503_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorChapter',
            fields=[
            ],
            options={
                'verbose_name': '专题章节',
                'verbose_name_plural': '专题章节',
                'proxy': True,
                'indexes': [],
            },
            bases=('db.chapter',),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.random, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.random, max_length=4, primary_key=True, serialize=False, verbose_name='专题id'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.random, max_length=6, primary_key=True, serialize=False, verbose_name='章节id'),
        ),
    ]
