# Generated by Django 2.0.7 on 2019-04-02 21:38

import DjangoUeditor.models
from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20190402_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=DjangoUeditor.models.UEditorField(blank=True, max_length=300, verbose_name='作者回复'),
        ),
    ]
