# Generated by Django 2.0.7 on 2019-04-02 21:53

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20190402_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='message',
            name='nickname',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=12, primary_key=True, serialize=False),
        ),
    ]
