# Generated by Django 2.0.7 on 2019-04-02 23:20

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20190402_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='mod',
        ),
        migrations.AddField(
            model_name='comment',
            name='rep',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='回复时间'),
        ),
        migrations.AddField(
            model_name='message',
            name='rep',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='回复时间'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=12, primary_key=True, serialize=False),
        ),
    ]
