# Generated by Django 2.0.7 on 2019-04-05 00:54

from django.db import migrations, models
import shortuuid.main


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20190404_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='id',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.random, max_length=12, primary_key=True, serialize=False),
        ),
    ]
