"""
Django settings for ljx project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import pymysql

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8=2y6u_5e=3mx0ut5hct!4t)g7gjy@7j_r$-(jv0&#n%v+@p=!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

pymysql.install_as_MySQLdb()

ALLOWED_HOSTS = [
    'www.lujianxin.com',
    'www.lujianxin.cn',
    'lujianxin.com',
    'lujianxin.cn',
    '127.0.0.1',
]

# 网站开始运营时间
START = '2018-03-30'

SERVER = 'https://{}'.format(ALLOWED_HOSTS[0])
# SERVER = 'https://{}'.format(ALLOWED_HOSTS[0])
DEFAULT_UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 主要业务模块
    'ljx',
    'db',
    # 功能拓展模块
    'crispy_forms',
    'reversion',
    'xadmin',
    'DjangoUeditor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 以下是自定义中间件
    'db.my_middlewares.AllMethodSupportMiddleware',
    'db.my_middlewares.VisitorAuthenticationMiddleware',
    'db.my_middlewares.VisitCountMiddleware',
    'db.my_middlewares.LinkClickMiddleware',
]

ROOT_URLCONF = 'ljx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                # 以下为自定义模板上下文
                'db.my_context_processors.site',
                'db.my_context_processors.cats',
                'db.my_context_processors.site_count',
                'db.my_context_processors.most_read',
                'db.my_context_processors.notice',
                'db.my_context_processors.recommend',
                # 拟定用户登录全局上下文
                'db.my_context_processors.visit_auth'
            ],
        },
    },
]

WSGI_APPLICATION = 'ljx.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'STATIC')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 站点信息
SITE = {
    'dns': ALLOWED_HOSTS[0],
    'host': 'https://{}'.format(ALLOWED_HOSTS[0]),
    'name': '陆鉴鑫的博客',
    'email': {
        'jubao': 'jubao@lujianxin.com',
        'tougao': 'tougao@lujianxin.com',
        'support': 'support@lujianxin.com',
        'me': 'jeeyshe@gmail.com',
    },
    'icp': '浙ICP备18053740号-2',
    # 各种搜索引擎验证码
    'search_engine_metas': {
        'baidu-site-verification': '5amdMOKaXx',
        'google-site-verification': 'C2ujkHLAjxkyD2SXrnXNeoZum0YsZcl832GvR3XBTw4',
    },
    # 我的名片
    'webname': 'jeeyshe.Ru | 杰西.鲁',
    'major': 'python, golang后端工程师',
    'location': '浙江省-杭州市',
}

# 文章缩略文本长度
ART_DESC_LENGTH = 200

# 评论和留言缩略长度
COM_DESC_LENGTH = MSG_DESC_LENGTH = 20
