"""
Django settings for ljx project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import re
import pymysql

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8=2y6u_5e=3mx0ut5hct!4t)g7gjy@7j_r$-(jv0&#n%v+@p=!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 维护期间阻止用户登录后台产生新的数据
UPGRADING = False

pymysql.install_as_MySQLdb()

ALLOWED_HOSTS = [
    'www.lujianxin.com',
    '127.0.0.1',
]

# 网站开始运营时间
START = '2019-04-15'

SERVER = 'https://{}'.format(ALLOWED_HOSTS[0])
DEFAULT_UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

MAIN_APPS = [
    # 主要业务模块
    'ljx',
    'db',
]
INSTALLED_APPS.extend(MAIN_APPS)
EXTRA_APPS = [
    # 功能拓展模块
    'crispy_forms',
    'reversion',
    'xadmin',
    'DjangoUeditor',
]
INSTALLED_APPS.extend(EXTRA_APPS)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 以下是自定义中间件
    'db.my_middlewares.AllMethodSupportMiddleware',
    'db.my_middlewares.VisitCountMiddleware',
    # 以下是开启缓存中间件
    'django.middleware.cache.CacheMiddleware',
]

ROOT_URLCONF = 'ljx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                # 以下为自定义模板上下文
                'db.my_context_processors.site',
                'db.my_context_processors.cats',
                'db.my_context_processors.site_count',
                'db.my_context_processors.most_read',
                'db.my_context_processors.notice',
                'db.my_context_processors.recommend',
                'db.my_context_processors.live_re',
                'db.my_context_processors.links',
            ],
        },
    },
]

WSGI_APPLICATION = 'ljx.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'ishare',
    #     'USER': 'root',
    #     'PASSWORD': 'ljX.07',
    #     'HOST': 'lujianxin.com',
    #     'PORT': '3306',
    # }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'STATIC')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTH_USER_MODEL = 'db.UserAccount'
AUTHENTICATION_BACKENDS = (
    'db.utils.EmailAuthBackend',
)

# 云评论插件的账户信息
LIVE_RE = {
    'data_id': 'city',
    'data_uid': 'MTAyMC80MzY3NS8yMDIxNQ==',
}

# 密码重置链接一天内有效
PASSWORD_RESET_TIMEOUT_DAYS = 1

# 站点信息
SITE = {
    'dns': ALLOWED_HOSTS[0],
    'host': 'https://{}'.format(ALLOWED_HOSTS[0]),
    'name': '陆鉴鑫的博客',
    'me': 'https://me.lujianxin.com',
    'email': {
        'jubao': 'jubao@lujianxin.com',
        'tougao': 'tougao@lujianxin.com',
        'support': 'support@lujianxin.com',
        'me': 'jeeyshe@gmail.com',
    },
    'icp': '浙ICP备18053740号-2',
    # 各种搜索引擎验证码
    'search_engine_metas': {
        'baidu-site-verification': '5amdMOKaXx',
        'google-site-verification': 'C2ujkHLAjxkyD2SXrnXNeoZum0YsZcl832GvR3XBTw4',
        '360-site-verification': '8a43aac6e4ecbfb7849b61c40cdebd76',
        'shenma-site-verification': '61038a23c3906f69d8ec598c57a5988c_1556268317',
        'sogou_site_verification': '7LJQRWpzdw',
        'msvalidate.01': '725274B06FEC1DAE34DA835E37A6D5D5',
    },
    'UPGRADING': UPGRADING,
}

# 文章缩略文本长度
ART_DESC_LENGTH = 200

# 评论和留言缩略长度
COM_DESC_LENGTH = MSG_DESC_LENGTH = 20

# 缓存配置
#########
# CACHE #
#########

CACHE_MIDDLEWARE_KEY_PREFIX = ''
CACHE_MIDDLEWARE_SECONDS = 180
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHES = {
    # 默认使用的库，session，csrf等存储
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "PASSWORD": "ljX.07",
        }
    },
    # 重置密码token
    "one": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "PASSWORD": "ljX.07",
        }
    },
    # 2号3号库用作celery的任务队列

    # 专做本站访问次数记录
    "four": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/4",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 10},
            "PASSWORD": "ljX.07",
        }
    },
}

############
# SESSIONS #
############

# Cache to store session data if using the cache session backend.
SESSION_CACHE_ALIAS = 'default'
# Cookie name. This can be whatever you want.
SESSION_COOKIE_NAME = 'sessionid'
# Age of cookie, in seconds (default: 2 weeks).
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7 * 2
# The path of the session cookie.
SESSION_COOKIE_PATH = '/'
SESSION_EXPIRE_AT_BROWSER_CLOSE = DEBUG
# class to serialize session data
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
# 基于内存和redis双缓存
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
DJANGO_REDIS_IGNORE_EXCEPTIONS = True  # 忽略异常

LOGOUT_REDIRECT_URL = '/'
CSRF_USE_SESSIONS = True

# celery配置
CELERY_BROKER_URL = BROKER_URL = 'redis://:ljX.07@127.0.0.1:6379/2'
CELERY_RESULT_BACKEND = 'redis://:ljX.07@127.0.0.1:6379/3'
CELERY_CACHE_BACKEND = 'django-cache'
BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 3600,
    'fanout_prefix': True,
}

# ----------本站系统所用email配置----------
SERVER_EMAIL = 'support@lujianxin.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.exmail.qq.com'
EMAIL_PORT = 465

EMAIL_USE_LOCALTIME = False

# Optional SMTP authentication information for EMAIL_HOST.
EMAIL_HOST_USER = 'support@lujianxin.com'
EMAIL_HOST_PASSWORD = 'ljX.07'
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = None
EMAIL_TIMEOUT = None

DEFAULT_FROM_EMAIL = 'support@lujianxin.com'
EMAIL_SUBJECT_PREFIX = '[陆鉴鑫的博客]'

LIST_INFO = {
    'page_size': 30,
    'A': """其实我一直想写点什么，现在终于着手试一下。曾经也算个文艺青年，经过生活琐事的稀释，
    现在也不剩多少墨水了。单独开出这个栏目，希望重拾我的文学梦想。
    """,
    'B': """如果有人与我们分享过一个夏季，我们的记忆就会在生命中相互呼唤，
    如果我们曾经怀着相同的理想并肩前行过一段岁月，到了最后会不会在彼此的记忆中植满百合？
    """,
    'tag': '此标签检索到以下结果，如果没有你想找的，也可点击右上角进行站内搜索。',
}

# ------------simpleui配置

SIMPLEUI_HOME_TITLE = '后台首页'
SIMPLEUI_LOGO = 'https://avatars2.githubusercontent.com/u/13655483?s=60&v=4'
SIMPLEUI_HOME_INFO = True
SIMPLEUI_HOME_QUICK = True
SIMPLEUI_HOME_ACTION = True
SIMPLEUI_ANALYSIS = False
SIMPLEUI_CONFIG = {
    'system_keep': True,
    # 'menus': [{
    #     'name': 'Simpleui',
    #     'icon': 'fas fa-code',
    #     'url': 'https://gitee.com/tompeppa/simpleui'
    # }, {
    #     'app': 'auth',
    #     'name': '权限认证',
    #     'icon': 'fas fa-user-shield',
    #     'models': [{
    #         'name': '用户',
    #         'icon': 'fa fa-user',
    #         'url': 'auth/user/'
    #     }]
    # }, {
    #     'name': '测试',
    #     'icon': 'fa fa-file',
    #     'models': [{
    #         'name': 'Baidu',
    #         'url': 'http://baidu.com',
    #         'icon': 'far fa-surprise'
    #     }, {
    #         'name': '内网穿透',
    #         'url': 'https://www.wezoz.com',
    #         'icon': 'fab fa-github'
    #     }]
    # }]
}
